apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
      - image: shekhar123reddy/ganesh:latest
        name: app-ui
        ports:
        - containerPort: 5004
